-- Insertion des noms des prestataires dans l'annuaire
INSERT INTO Annuaire (name) VALUES
('Spie'),
('Chubb'),
('BPI'),
('Siemens'),
('Bureau Veritas'),
('Jungheinrich'),
('Virly'),
('Toyota'),
('Assa Abloy'),
('AEP'),
('Polysécurité'),
('ADS'),
('Avipur'),
('BSA'),
('Claude Monnot'),
('Aerocom'),
('Culligan'),
('SBC'),
('Girardeau'),
('DS Contrôle'),
('Apave'),
('Mabeo'),
('Ajuva');
